version: '3.8'

services:
  app:
    build:
      context: .
    restart: on-failure
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lotteryDB
    ports:
      - "8888:8888"
    networks:
      - spring-app

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lotteryDB
    ports:
      - "5435:5432"
    networks:
      - spring-app
networks:
  spring-app:
volumes:
  springdata: